################################################
## Inputs
################################################

input_number:
  light_level:
    name: The amount of environmental light
    icon: mdi:candle
    initial: 0
    min: 0
    max: 4
    step: 1

input_boolean:
  hallway_light:
    name: The hallway light is turned on
    initial: "off"

################################################
## Scripts
################################################

script:
  lights_do_tick:
    alias: Lights - Do tick
    sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.sleep_mode
            state: 'on'
          sequence:
            - scene: scene.living_room_lights_off
            - scene: scene.exterior_lights_off
        - conditions:
          - condition: state
            entity_id: input_number.light_level
            state: '4.0'
          sequence:
            - scene: scene.living_room_lights_off
            - scene: scene.exterior_lights_off
        - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: person.stefan
                state: home
          sequence:
            - scene: scene.living_room_lights_away
            - scene: scene.exterior_lights_away
        - conditions:
          - condition: state
            entity_id: input_number.light_level
            state: '3.0'
          sequence:
            - scene: scene.living_room_lights_on_1_3
            - scene: scene.exterior_lights_off
        - conditions:
          - condition: state
            entity_id: input_number.light_level
            state: '2.0'
          sequence:
            - scene: scene.living_room_lights_on_2_3
            - scene: scene.exterior_lights_off
        - conditions:
          - condition: state
            entity_id: input_number.light_level
            state: '1.0'
          sequence:
            - scene: scene.living_room_lights_on_3_3
            - scene: scene.exterior_lights_on_1_2
        - conditions:
          - condition: state
            entity_id: input_number.light_level
            state: '0.0'
          sequence:
            - scene: scene.living_room_lights_on_3_3
            - scene: scene.exterior_lights_on_2_2

################################################
## Automations
################################################

automation:
  - alias: Lights - Do tick
    trigger:
      - platform: state
        entity_id: person.stefan
        from: "home"
      - platform: state
        entity_id: person.stefan
        to: "home"
      - platform: state
        entity_id: input_number.light_level
    action:
      - service: script.lights_do_tick

  - alias: Lights - Level 0
    trigger:
      - platform: sun
        event: sunset
        offset: '00:15:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 0

  - alias: Lights - Level 1
    trigger:
      - platform: sun
        event: sunrise
        offset: '-00:30:00'
      - platform: sun
        event: sunset
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 1

  - alias: Lights - Level 2
    trigger:
      - platform: sun
        event: sunrise
        offset: '-00:15:00'
      - platform: sun
        event: sunset
        offset: '-00:15:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 2

  - alias: Lights - Level 3
    trigger:
      - platform: sun
        event: sunrise
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 3

  - alias: Lights - Level 4
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:15:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 4

  - alias: Lights - Hallway lamp - Turn off when opening front door
    description: To prevent critters from flying to the light
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_front_door_door_state
        to: "on"
    condition:
      - condition: state
        entity_id: switch.hallway_lights_switch_1
        state: "on"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.hallway_light
      - service: switch.turn_off
        target:
          entity_id: switch.hallway_lights_switch_1
    mode: single

  - alias: Lights - Hallway lamp - Resume when closing front door
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_front_door_door_state
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.hallway_light
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.hallway_light
      - service: switch.turn_on
        target:
          entity_id: switch.hallway_lights_switch_1
    mode: single

################################################
## Scenes
################################################

scene:
  - name: Exterior lights on 1/2
    entities:
      switch.hallway_lights_switch_2:
        state: off
      switch.back_garden_awning_lights_switch_1:
        state: off
      switch.shed_light_switch:
        state: on
    icon: hass:coach-light

  - name: Exterior lights on 2/2
    entities:
      switch.hallway_lights_switch_2:
        state: on
      switch.back_garden_awning_lights_switch_1:
        state: on
      switch.shed_light_switch:
        state: on
    icon: hass:coach-light

  - name: Exterior lights away
    entities:
      switch.hallway_lights_switch_2:
        state: on
      switch.back_garden_awning_lights_switch_1:
        state: off
      switch.shed_light_switch:
        state: on
    icon: hass:coach-light

  - name: Exterior lights off
    entities:
      switch.hallway_lights_switch_2:
        state: off
      switch.back_garden_awning_lights_switch_1:
        state: off
      switch.shed_light_switch:
        state: off
    icon: hass:coach-light

  - name: Living room lights on 1/3
    entities:
      switch.living_room_tv_light_switch:
        state: on
      switch.living_room_couch_light_switch:
        state: off
      switch.living_room_front_light_switch:
        state: off
      light.living_room_dinner_table_dimmer:
        state: off
      light.kitchen_lights_dimmer:
        state: on
        brightness_pct: 1
    icon: hass:light

  - name: Living room lights on 2/3
    entities:
      switch.living_room_tv_light_switch:
        state: on
      switch.living_room_couch_light_switch:
        state: on
      switch.living_room_front_light_switch:
        state: off
      light.living_room_dinner_table_dimmer:
        state: on
        brightness_pct: 10
      light.kitchen_lights_dimmer:
        state: on
        brightness_pct: 5
    icon: hass:light

  - name: Living room lights on 3/3
    entities:
      switch.living_room_tv_light_switch:
        state: on
      switch.living_room_couch_light_switch:
        state: on
      switch.living_room_front_light_switch:
        state: on
      light.living_room_dinner_table_dimmer:
        state: on
        brightness_pct: 40
      light.kitchen_lights_dimmer:
        state: on
        brightness_pct: 10
    icon: hass:light

  - name: Living room lights away
    entities:
      switch.living_room_tv_light_switch:
        state: off
      switch.living_room_couch_light_switch:
        state: off
      switch.living_room_front_light_switch:
        state: off
      light.living_room_dinner_table_dimmer:
        state: on
        brightness_pct: 1
      light.kitchen_lights_dimmer:
        state: off
    icon: hass:light

  - name: Living room lights off
    entities:
      switch.living_room_tv_light_switch:
        state: off
      switch.living_room_couch_light_switch:
        state: off
      switch.living_room_front_light_switch:
        state: off
      light.living_room_dinner_table_dimmer:
        state: off
      light.kitchen_lights_dimmer:
        state: off
    icon: hass:light

  - name: Night lights on
    entities:
      switch.bedroom_left_night_light_switch:
        state: on
      switch.bedroom_right_night_light_switch:
        state: on
    icon: hass:lights

  - name: Night lights off
    entities:
      switch.bedroom_left_night_light_switch:
        state: off
      switch.bedroom_right_night_light_switch:
        state: off
    icon: mdi:lights-outline
