################################################
## Inputs
################################################

input_number:
  light_level:
    name: The amount of environmental light
    icon: mdi:candle
    initial: 0
    min: 0
    max: 4
    step: 1

input_boolean:
  hallway_light:
    name: The hallway light is turned on
    initial: "off"

################################################
## Automations
################################################

automation:
  - alias: Variable - Light level to 4 at sunrise
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 4

  - alias: Variable - Light level to 3 before sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 3

  - alias: Variable - Light level to 2 before sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:15:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 2

  - alias: Variable - Light level to 1 at sunset
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 1

  - alias: Variable - Light level to 0 after sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '00:15:00'
    action:
      - service: input_number.set_value
        entity_id: input_number.light_level
        data:
          value: 0

  - alias: Lights - Turn on 1/4
    trigger:
      - platform: state
        entity_id: input_number.light_level
        to: '3.0'
    action:
      - scene: scene.living_room_lights_on_1_3
    mode: single

  - alias: Lights - Turn on 2/4
    trigger:
      - platform: state
        entity_id: input_number.light_level
        to: '2.0'
    action:
      - scene: scene.living_room_lights_on_2_3
    mode: single

  - alias: Lights - Turn on 3/4
    trigger:
      - platform: state
        entity_id: input_number.light_level
        to: '1.0'
    action:
      - scene: scene.living_room_lights_on_3_3
      - scene: scene.exterior_lights_on_1_2
    mode: single

  - alias: Lights - Turn on 4/4
    trigger:
      - platform: state
        entity_id: input_number.light_level
        to: '0.0'
    action:
      - scene: scene.exterior_lights_on_2_2
    mode: single

  - alias: Lights - Turn off
    trigger:
      - platform: state
        entity_id: input_number.light_level
        to: '4.0'
    action:
      - scene: scene.living_room_lights_off
      - scene: scene.exterior_lights_off
    mode: single

  - alias: Lights - Hallway lamp - Turn off when opening front door
    description: To prevent critters from flying to the light
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_front_door_door_state
        to: "on"
    condition:
      - condition: state
        entity_id: switch.hallway_lights_switch_1
        state: "on"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.hallway_light
      - service: switch.turn_off
        target:
          entity_id: switch.hallway_lights_switch_1
    mode: single

  - alias: Lights - Hallway lamp - Resume when closing front door
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_front_door_door_state
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.hallway_light
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.hallway_light
      - service: switch.turn_on
        target:
          entity_id: switch.hallway_lights_switch_1
    mode: single

################################################
## Scenes
################################################

scene:
  - name: Exterior lights on 1/2
    entities:
      switch.hallway_lights_switch_2:
        friendly_name: Porch light
        state: off
      switch.back_garden_awning_lights_switch_1:
        friendly_name: Rear lights
        state: off
      switch.shed_light_switch:
        friendly_name: Shed light
        state: on
    icon: hass:coach-light

  - name: Exterior lights on 2/2
    entities:
      switch.hallway_lights_switch_2:
        friendly_name: Porch light
        state: on
      switch.back_garden_awning_lights_switch_1:
        friendly_name: Rear lights
        state: on
      switch.shed_light_switch:
        friendly_name: Shed light
        state: on
    icon: hass:coach-light

  - name: Exterior lights off
    entities:
      switch.hallway_lights_switch_2:
        friendly_name: Porch light
        state: off
      switch.back_garden_awning_lights_switch_1:
        friendly_name: Rear lights
        state: off
      switch.shed_light_switch:
        friendly_name: Shed light
        state: off
    icon: hass:coach-light

  - name: Living room lights on 1/3
    entities:
      switch.living_room_tv_light_switch:
        friendly_name: Living room-TV light_switch
        state: on
      switch.living_room_couch_light_switch:
        friendly_name: Living room-Couch light_switch
        state: off
      switch.living_room_front_light_switch:
        friendly_name: Living room-Front light_switch
        state: off
    icon: hass:light

  - name: Living room lights on 2/3
    entities:
      switch.living_room_tv_light_switch:
        friendly_name: Living room-TV light_switch
        state: on
      switch.living_room_couch_light_switch:
        friendly_name: Living room-Couch light_switch
        state: on
      switch.living_room_front_light_switch:
        friendly_name: Living room-Front light_switch
        state: off
    icon: hass:light

  - name: Living room lights on 3/3
    entities:
      switch.living_room_tv_light_switch:
        friendly_name: Living room-TV light_switch
        state: on
      switch.living_room_couch_light_switch:
        friendly_name: Living room-Couch light_switch
        state: on
      switch.living_room_front_light_switch:
        friendly_name: Living room-Front light_switch
        state: on
    icon: hass:light

  - name: Living room lights off
    entities:
      switch.living_room_tv_light_switch:
        friendly_name: Living room-TV light_switch
        state: off
      switch.living_room_couch_light_switch:
        friendly_name: Living room-Couch light_switch
        state: off
      switch.living_room_front_light_switch:
        friendly_name: Living room-Front light_switch
        state: off
    icon: hass:light

  - name: Night lights on
    entities:
      switch.bedroom_left_night_light_switch:
        friendly_name: Bedroom-Night light right_switch
        state: on
      switch.bedroom_right_night_light_switch:
        friendly_name: Bedroom-Night light left_switch
        state: on
    icon: hass:lights

  - name: Night lights off
    entities:
      switch.bedroom_left_night_light_switch:
        friendly_name: Bedroom-Night light left_switch
        state: off
      switch.bedroom_right_night_light_switch:
        friendly_name: Bedroom-Night light right_switch
        state: off
    icon: mdi:lights-outline
